# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-10 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('dogs', 'dogs'), ('cats', 'cats')], max_length=255)),
            ],
        ),
    ]
