# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-11 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_image_image_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='pic_image',
        ),
    ]
