# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-11 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_remove_image_pic_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='pic_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
