# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-11 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_image_pic_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('dogs', 'dogs'), ('cats', 'cats'), ('people', 'people'), ('flowers', 'flowers')], max_length=255),
        ),
    ]
