# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-11 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_auto_20191011_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('Kicukiro', 'Kicukiro'), ('Gasabo', 'Gasabo'), ('Park', 'Park'), ('USA', 'USA')], max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Location',
            },
        ),
        migrations.AddField(
            model_name='image',
            name='image_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='images.Location'),
        ),
    ]
