# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-11 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_auto_20191011_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_location',
            new_name='location',
        ),
    ]
