# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-13 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0011_auto_20191011_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('dogs', 'dogs'), ('cats', 'cats'), ('people', 'people'), ('flowers', 'flowers')], max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(choices=[('UK', 'UK'), ('RWANDA', 'RWANDA'), ('CANADA', 'CANADA'), ('USA', 'USA')], max_length=255),
        ),
    ]
