# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-13 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0012_auto_20191013_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
